language: python 
dist: xenial
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install: 
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script: 
  - python setup.py test
env: 
  TRAVIS=1
